### ISSUE TITLE
Methods do not work if duplicate = false

### ISSUE THREAD

**Issue by b4tch** [ComputerWolf/SlickNav#131] opened 2016-03-24 11:40 UTC
If the duplicate option is set to false, I could not get the 'toggle', 'open', or 'close' methods to work.  Turns out I could remove this option without issue to my app, but though I'd give you/everyone a heads up.

**Comment by ComputerWolf** [comment] 2016-03-24 16:31
@b4tch This has been hopefully fixed in the latest version. The issue is that IDs were stripped from the menu by default and if you were targeting the menu that way with the `open` method, it would do nothing. This can be fixed by utilizing a variable after initialization, but in the new version IDs are not removed by default is `duplicate` is false.

**Closed by ComputerWolf** 2016-03-24 16:31 UTC
